### ISSUE TITLE
A schedule gets sucked into a black hole

### ISSUE THREAD

**Issue by seiyanuta** [seiyanuta/busybook#6]
```
I, [2016-02-14T16:36:26.636370 #27373]  INFO -- : Started PUT "/calendar/Private/815CC2BD-F124-42D1-9008-242DB952791B.ics" for 103.41.62.117 at 2016-02-14 16:36:26 +0900
I, [2016-02-14T16:36:26.641510 #27373]  INFO -- : Processing by CalendarController#put as ICS
I, [2016-02-14T16:36:26.641716 #27373]  INFO -- :   Parameters: {"calendar"=>"Private", "calendar_object"=>"815CC2BD-F124-42D1-9008-242DB952791B"}
D, [2016-02-14T16:36:26.643375 #27373] DEBUG -- :   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "seiya"]]
D, [2016-02-14T16:36:26.646512 #27373] DEBUG -- :   Calendar Load (0.5ms)  SELECT  "calendars".* FROM "calendars" WHERE "calendars"."uri" = $1 LIMIT 1  [["uri", "Private"]]
D, [2016-02-14T16:36:26.649578 #27373] DEBUG -- :   Schedule Load (0.7ms)  SELECT  "schedules".* FROM "schedules" WHERE "schedules"."uri" = $1  ORDER BY "schedules"."id" ASC LIMIT 1  [["uri", "815CC2BD-F124-42D1-9008-242DB952791B"]]
D, [2016-02-14T16:36:26.651938 #27373] DEBUG -- :    (0.4ms)  BEGIN
D, [2016-02-14T16:36:26.676355 #27373] DEBUG -- :   SQL (21.5ms)  INSERT INTO "schedules" ("uri", "ics", "component", "date_start", "date_end", "calendar_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["uri", "815CC2BD-F124-42D1-9008-242DB952791B"], ["ics", "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.11.3//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Asia/Tokyo\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0900\r\nRRULE:FREQ=YEARLY;UNTIL=19510505T170000Z;BYMONTH=5;BYDAY=1SU\r\nDTSTART:19500507T020000\r\nTZNAME:GMT+9\r\nTZOFFSETTO:+1000\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+1000\r\nDTSTART:19510908T020000\r\nTZNAME:GMT+9\r\nTZOFFSETTO:+0900\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nCREATED:20160214T073624Z\r\nUID:815CC2BD-F124-42D1-9008-242DB952791B\r\nDTEND;TZID=Asia/Tokyo:20160218T093000\r\nTRANSP:OPAQUE\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:New Event\r\nDTSTART;TZID=Asia/Tokyo:20160218T083000\r\nDTSTAMP:20160214T073624Z\r\nSEQUENCE:0\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n"], ["component", "VEVENT"], ["date_start", "2016-02-17 23:30:00.000000"], ["date_end", "2016-02-18 00:30:00.000000"], ["calendar_id", 1], ["created_at", "2016-02-14 07:36:26.653115"], ["updated_at", "2016-02-14 07:36:26.653115"]]
D, [2016-02-14T16:36:26.681606 #27373] DEBUG -- :   SQL (1.0ms)  INSERT INTO "changes" ("calendar_id", "uri", "is_delete", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["calendar_id", 1], ["uri", "815CC2BD-F124-42D1-9008-242DB952791B"], ["is_delete", "f"], ["created_at", "2016-02-14 07:36:26.679104"], ["updated_at", "2016-02-14 07:36:26.679104"]]
D, [2016-02-14T16:36:26.684644 #27373] DEBUG -- :    (1.4ms)  COMMIT
I, [2016-02-14T16:36:26.685603 #27373]  INFO -- : Completed 201 Created in 44ms (ActiveRecord: 26.1ms)
I, [2016-02-14T16:36:26.711816 #27373]  INFO -- : Started GET "/calendar/Private/815CC2BD-F124-42D1-9008-242DB952791B.ics" for 103.41.62.117 at 2016-02-14 16:36:26 +0900
I, [2016-02-14T16:36:26.717374 #27373]  INFO -- : Processing by CalendarController#get as ICS
I, [2016-02-14T16:36:26.717599 #27373]  INFO -- :   Parameters: {"calendar"=>"Private", "calendar_object"=>"815CC2BD-F124-42D1-9008-242DB952791B"}
D, [2016-02-14T16:36:26.719718 #27373] DEBUG -- :   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "seiya"]]
D, [2016-02-14T16:36:26.722158 #27373] DEBUG -- :   Schedule Load (0.7ms)  SELECT  "schedules".* FROM "schedules" WHERE "schedules"."uri" = $1 LIMIT 1  [["uri", "815CC2BD-F124-42D1-9008-242DB952791B"]]
I, [2016-02-14T16:36:26.724102 #27373]  INFO -- :   Rendered text template (0.4ms)
I, [2016-02-14T16:36:26.724505 #27373]  INFO -- : Completed 200 OK in 7ms (Views: 1.2ms | ActiveRecord: 1.4ms)
I, [2016-02-14T16:36:31.686513 #27370]  INFO -- : Started MOVE "/calendar/CC1E720F-8D5C-440F-961D-8F83F0A59E0B/9804288B-CF8A-4D90-A434-FE0F1CE0C5C9" for 103.41.62.117 at 2016-02-14 16:36:31 +0900
F, [2016-02-14T16:36:31.712503 #27370] FATAL -- : 
ActionController::RoutingError (No route matches [MOVE] "/calendar/CC1E720F-8D5C-440F-961D-8F83F0A59E0B/9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  unicorn (5.0.1) lib/unicorn/http_server.rb:562:in `process_client'
  unicorn (5.0.1) lib/unicorn/http_server.rb:658:in `worker_loop'
  unicorn (5.0.1) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  unicorn (5.0.1) lib/unicorn/http_server.rb:132:in `start'
  unicorn (5.0.1) bin/unicorn:126:in `<top (required)>'
  /usr/local/bin/unicorn:23:in `load'
  /usr/local/bin/unicorn:23:in `<main>'


I, [2016-02-14T16:36:31.822584 #27370]  INFO -- : Started PUT "/calendar/Private/9804288B-CF8A-4D90-A434-FE0F1CE0C5C9" for 103.41.62.117 at 2016-02-14 16:36:31 +0900
I, [2016-02-14T16:36:31.826694 #27370]  INFO -- : Processing by CalendarController#put as */*
I, [2016-02-14T16:36:31.826834 #27370]  INFO -- :   Parameters: {"calendar"=>"Private", "calendar_object"=>"9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"}
D, [2016-02-14T16:36:31.828233 #27370] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "seiya"]]
D, [2016-02-14T16:36:31.830446 #27370] DEBUG -- :   Calendar Load (0.4ms)  SELECT  "calendars".* FROM "calendars" WHERE "calendars"."uri" = $1 LIMIT 1  [["uri", "Private"]]
D, [2016-02-14T16:36:31.832516 #27370] DEBUG -- :   Schedule Load (0.6ms)  SELECT  "schedules".* FROM "schedules" WHERE "schedules"."uri" = $1  ORDER BY "schedules"."id" ASC LIMIT 1  [["uri", "9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"]]
D, [2016-02-14T16:36:31.835123 #27370] DEBUG -- :    (0.4ms)  BEGIN
D, [2016-02-14T16:36:31.839353 #27370] DEBUG -- :   SQL (0.9ms)  UPDATE "schedules" SET "ics" = $1, "calendar_id" = $2, "updated_at" = $3 WHERE "schedules"."id" = $4  [["ics", "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.11.3//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VEVENT\r\nCREATED:20160207T114156Z\r\nUID:9804288B-CF8A-4D90-A434-FE0F1CE0C5C9\r\nDTEND;VALUE=DATE:20160218\r\nTRANSP:OPAQUE\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:粗大ゴミの日\r\nDTSTART;VALUE=DATE:20160217\r\nDTSTAMP:20160214T073631Z\r\nLAST-MODIFIED:20160207T114156Z\r\nSEQUENCE:0\r\nURL;VALUE=URI:message:%3C624726435.466.1454845239617.JavaMail.root@10.1.\r\n 200.118%3E\r\nBEGIN:VALARM\r\nX-WR-ALARMUID:7A287FA9-CD91-42CE-9816-A13DEC4654E9\r\nUID:7A287FA9-CD91-42CE-9816-A13DEC4654E9\r\nTRIGGER:-PT15H\r\nX-APPLE-DEFAULT-ALARM:TRUE\r\nATTACH;VALUE=URI:Basso\r\nACTION:AUDIO\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n"], ["calendar_id", 1], ["updated_at", "2016-02-14 07:36:31.837214"], ["id", 484]]
D, [2016-02-14T16:36:31.842486 #27370] DEBUG -- :   SQL (0.5ms)  INSERT INTO "changes" ("calendar_id", "uri", "is_delete", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["calendar_id", 1], ["uri", "9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"], ["is_delete", "f"], ["created_at", "2016-02-14 07:36:31.841048"], ["updated_at", "2016-02-14 07:36:31.841048"]]
D, [2016-02-14T16:36:31.844460 #27370] DEBUG -- :    (1.0ms)  COMMIT
I, [2016-02-14T16:36:31.845178 #27370]  INFO -- : Completed 201 Created in 18ms (ActiveRecord: 4.3ms)
I, [2016-02-14T16:36:31.862891 #27373]  INFO -- : Started DELETE "/calendar/CC1E720F-8D5C-440F-961D-8F83F0A59E0B/9804288B-CF8A-4D90-A434-FE0F1CE0C5C9" for 103.41.62.117 at 2016-02-14 16:36:31 +0900
I, [2016-02-14T16:36:31.866850 #27373]  INFO -- : Processing by CalendarController#delete as */*
I, [2016-02-14T16:36:31.867085 #27373]  INFO -- :   Parameters: {"calendar"=>"CC1E720F-8D5C-440F-961D-8F83F0A59E0B", "calendar_object"=>"9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"}
D, [2016-02-14T16:36:31.868572 #27373] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "seiya"]]
D, [2016-02-14T16:36:31.870278 #27373] DEBUG -- :   Calendar Load (0.4ms)  SELECT  "calendars".* FROM "calendars" WHERE "calendars"."uri" = $1 LIMIT 1  [["uri", "CC1E720F-8D5C-440F-961D-8F83F0A59E0B"]]
D, [2016-02-14T16:36:31.871302 #27373] DEBUG -- :    (0.3ms)  BEGIN
D, [2016-02-14T16:36:31.872453 #27373] DEBUG -- :   Schedule Load (0.4ms)  SELECT  "schedules".* FROM "schedules" WHERE "schedules"."uri" = $1 LIMIT 1  [["uri", "9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"]]
D, [2016-02-14T16:36:31.874350 #27373] DEBUG -- :   SQL (0.5ms)  DELETE FROM "schedules" WHERE "schedules"."id" = $1  [["id", 484]]
D, [2016-02-14T16:36:31.877805 #27373] DEBUG -- :   SQL (0.8ms)  INSERT INTO "changes" ("calendar_id", "uri", "is_delete", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["calendar_id", 4], ["uri", "9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"], ["is_delete", "t"], ["created_at", "2016-02-14 07:36:31.875639"], ["updated_at", "2016-02-14 07:36:31.875639"]]
D, [2016-02-14T16:36:31.905059 #27373] DEBUG -- :    (26.1ms)  COMMIT
I, [2016-02-14T16:36:31.906373 #27373]  INFO -- : Completed 204 No Content in 39ms (ActiveRecord: 28.9ms)
I, [2016-02-14T16:36:31.924127 #27373]  INFO -- : Started PROPFIND "/calendar/Private/9804288B-CF8A-4D90-A434-FE0F1CE0C5C9" for 103.41.62.117 at 2016-02-14 16:36:31 +0900
I, [2016-02-14T16:36:31.927926 #27373]  INFO -- : Processing by CalendarController#propfind as */*
I, [2016-02-14T16:36:31.928034 #27373]  INFO -- :   Parameters: {"calendar"=>"Private", "calendar_object"=>"9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"}
D, [2016-02-14T16:36:31.929282 #27373] DEBUG -- :   User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "seiya"]]
D, [2016-02-14T16:36:31.931137 #27373] DEBUG -- :   Calendar Load (0.3ms)  SELECT  "calendars".* FROM "calendars" WHERE "calendars"."uri" = $1 LIMIT 1  [["uri", "Private"]]
I, [2016-02-14T16:36:31.932259 #27373]  INFO -- : Completed 207 Multi-Status in 4ms (Views: 0.2ms | ActiveRecord: 0.7ms)
I, [2016-02-14T16:36:31.950704 #27373]  INFO -- : Started GET "/calendar/Private/9804288B-CF8A-4D90-A434-FE0F1CE0C5C9" for 103.41.62.117 at 2016-02-14 16:36:31 +0900
I, [2016-02-14T16:36:31.954424 #27373]  INFO -- : Processing by CalendarController#get as */*
I, [2016-02-14T16:36:31.954520 #27373]  INFO -- :   Parameters: {"calendar"=>"Private", "calendar_object"=>"9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"}
D, [2016-02-14T16:36:31.955734 #27373] DEBUG -- :   User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "seiya"]]
D, [2016-02-14T16:36:31.957456 #27373] DEBUG -- :   Schedule Load (0.6ms)  SELECT  "schedules".* FROM "schedules" WHERE "schedules"."uri" = $1 LIMIT 1  [["uri", "9804288B-CF8A-4D90-A434-FE0F1CE0C5C9"]]
I, [2016-02-14T16:36:31.958607 #27373]  INFO -- : Completed 404 Not Found in 4ms (ActiveRecord: 1.0ms)
```

**Comment by nuta** [comment]
I have to implement `MOVE` method.
